"""Generates src/index.ts for combank-ibmi-mcp."""
import pathlib

OUT = pathlib.Path(__file__).parent.parent / "src" / "index.ts"
OUT.parent.mkdir(exist_ok=True)

# fmt: off
TS = (
"#!/usr/bin/env node\n"
"/**\n"
" * ComBank IBM i MCP Server  v1.0.0\n"
" * Purpose-built for Commercial Bank of Ceylon IBM i environment.\n"
" * SSH-based, pre-configured for dev (172.16.112.200) / test (COMBTEST.COMBANK.NET).\n"
" */\n"
"\n"
"import { McpServer } from \"@modelcontextprotocol/sdk/server/mcp.js\";\n"
"import { StdioServerTransport } from \"@modelcontextprotocol/sdk/server/stdio.js\";\n"
"import { Client } from \"ssh2\";\n"
"import { z } from \"zod\";\n"
"import { config } from \"dotenv\";\n"
"import { writeFileSync, readFileSync, existsSync } from \"fs\";\n"
"import { resolve, dirname } from \"path\";\n"
"import { fileURLToPath } from \"url\";\n"
"\n"
"const __dirname = dirname(fileURLToPath(import.meta.url));\n"
"const ENV_FILE = resolve(__dirname, \"../.env\");\n"
"config({ path: ENV_FILE });\n"
"\n"
"// --- Environment Registry ---------------------------------------------------\n"
"\n"
"const ENVS: Record<string, { host: string; port: number }> = {\n"
"  dev:  { host: process.env.IBMI_HOST_DEV  ?? \"172.16.112.200\",      port: 22 },\n"
"  test: { host: process.env.IBMI_HOST_TEST ?? \"COMBTEST.COMBANK.NET\", port: 22 },\n"
"};\n"
"\n"
"// --- Runtime Config ---------------------------------------------------------\n"
"\n"
"function getEnv() {\n"
"  return {\n"
"    activeEnv:    process.env.IBMI_ENV            ?? \"dev\",\n"
"    user:         process.env.IBMI_USER           ?? \"lk08492\",\n"
"    password:     process.env.IBMI_PASSWORD       ?? \"\",\n"
"    libraryList:  (process.env.IBMI_LIBRARY_LIST  ?? \"IV15LCL,DHUHILIB,SASHILIB\").split(\",\").map(s => s.trim()),\n"
"    timeoutMs:    parseInt(process.env.IBMI_TIMEOUT_SEC     ?? \"90\")  * 1000,\n"
"    sqlTimeoutMs: parseInt(process.env.IBMI_SQL_TIMEOUT_SEC ?? \"120\") * 1000,\n"
"    poolMax:      parseInt(process.env.IBMI_POOL_MAX        ?? \"5\"),\n"
"    poolIdleMs:   parseInt(process.env.IBMI_POOL_IDLE_SEC   ?? \"120\") * 1000,\n"
"  };\n"
"}\n"
"\n"
"function saveEnv(patch: Partial<ReturnType<typeof getEnv> & { host?: string }>) {\n"
"  const raw  = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, \"utf8\") : \"\";\n"
"  const map: Record<string, string> = {};\n"
"  for (const l of raw.split(\"\\n\")) {\n"
"    const m = l.match(/^([A-Z_]+)=(.*)/);\n"
"    if (m) map[m[1]] = m[2];\n"
"  }\n"
"  if (patch.activeEnv  !== undefined) map[\"IBMI_ENV\"]           = patch.activeEnv;\n"
"  if ((patch as any).host !== undefined) {\n"
"    const e = patch.activeEnv ?? map[\"IBMI_ENV\"] ?? \"dev\";\n"
"    map[`IBMI_HOST_${e.toUpperCase()}`] = (patch as any).host;\n"
"  }\n"
"  if (patch.user         !== undefined) map[\"IBMI_USER\"]            = patch.user;\n"
"  if (patch.password     !== undefined) map[\"IBMI_PASSWORD\"]        = patch.password;\n"
"  if (patch.libraryList  !== undefined) map[\"IBMI_LIBRARY_LIST\"]    = (patch.libraryList as string[]).join(\",\");\n"
"  if (patch.timeoutMs    !== undefined) map[\"IBMI_TIMEOUT_SEC\"]     = String((patch.timeoutMs    as number) / 1000);\n"
"  if (patch.sqlTimeoutMs !== undefined) map[\"IBMI_SQL_TIMEOUT_SEC\"] = String((patch.sqlTimeoutMs as number) / 1000);\n"
"  if (patch.poolMax      !== undefined) map[\"IBMI_POOL_MAX\"]        = String(patch.poolMax);\n"
"  if (patch.poolIdleMs   !== undefined) map[\"IBMI_POOL_IDLE_SEC\"]   = String((patch.poolIdleMs   as number) / 1000);\n"
"  writeFileSync(ENV_FILE, Object.entries(map).map(([k,v]) => `${k}=${v}`).join(\"\\n\") + \"\\n\", \"utf8\");\n"
"  config({ path: ENV_FILE, override: true });\n"
"}\n"
"\n"
"// --- SSH Pool ---------------------------------------------------------------\n"
"\n"
"interface PoolEntry { conn: Client; lastUsed: number; busy: boolean }\n"
"const pool: PoolEntry[] = [];\n"
"let pruneTimer: ReturnType<typeof setInterval> | null = null;\n"
"\n"
"function startPrune() {\n"
"  if (pruneTimer) return;\n"
"  pruneTimer = setInterval(() => {\n"
"    const { poolIdleMs } = getEnv();\n"
"    const now = Date.now();\n"
"    for (let i = pool.length - 1; i >= 0; i--) {\n"
"      if (!pool[i].busy && now - pool[i].lastUsed > poolIdleMs) {\n"
"        pool[i].conn.end();\n"
"        pool.splice(i, 1);\n"
"      }\n"
"    }\n"
"  }, 30_000);\n"
"  pruneTimer.unref?.();\n"
"}\n"
"\n"
"function getConn(): Promise<{ conn: Client; release: () => void }> {\n"
"  return new Promise((resolve, reject) => {\n"
"    const cfg = getEnv();\n"
"    const envDef = ENVS[cfg.activeEnv];\n"
"    if (!envDef)       return reject(new Error(`Unknown environment: ${cfg.activeEnv}`));\n"
"    if (!cfg.password) return reject(new Error(\"No password set \u2014 run configure_connection first.\"));\n"
"\n"
"    for (const e of pool) {\n"
"      if (!e.busy) {\n"
"        e.busy = true; e.lastUsed = Date.now();\n"
"        return resolve({ conn: e.conn, release: () => { e.busy = false; e.lastUsed = Date.now(); } });\n"
"      }\n"
"    }\n"
"    if (pool.length >= cfg.poolMax) return reject(new Error(\"SSH pool exhausted\"));\n"
"\n"
"    const conn = new Client();\n"
"    conn.on(\"ready\", () => {\n"
"      const entry: PoolEntry = { conn, lastUsed: Date.now(), busy: true };\n"
"      pool.push(entry);\n"
"      startPrune();\n"
"      resolve({ conn, release: () => { entry.busy = false; entry.lastUsed = Date.now(); } });\n"
"    });\n"
"    conn.on(\"error\", reject);\n"
"    conn.connect({\n"
"      host:         cfg.user.includes(\"@\") ? cfg.user.split(\"@\")[1] : envDef.host,\n"
"      port:         envDef.port,\n"
"      username:     cfg.user.includes(\"@\") ? cfg.user.split(\"@\")[0] : cfg.user,\n"
"      password:     cfg.password,\n"
"      readyTimeout: 20_000,\n"
"      algorithms: {\n"
"        kex:           [\"diffie-hellman-group14-sha1\", \"diffie-hellman-group-exchange-sha256\"],\n"
"        serverHostKey: [\"ssh-rsa\", \"ecdsa-sha2-nistp256\"],\n"
"        cipher:        [\"aes128-ctr\", \"aes256-ctr\", \"3des-cbc\"],\n"
"        hmac:          [\"hmac-sha1\", \"hmac-sha2-256\"],\n"
"      },\n"
"    });\n"
"  });\n"
"}\n"
"\n"
"function execOnConn(conn: Client, command: string, timeoutMs: number): Promise<string> {\n"
"  return new Promise((resolve, reject) => {\n"
"    let out = \"\", stderr = \"\";\n"
"    const timer = setTimeout(() => reject(new Error(`Timed out after ${timeoutMs}ms`)), timeoutMs);\n"
"    conn.exec(command, (e, stream) => {\n"
"      if (e) { clearTimeout(timer); return reject(e); }\n"
"      stream.on(\"data\",        (d: Buffer) => (out    += d.toString()));\n"
"      stream.stderr.on(\"data\", (d: Buffer) => (stderr += d.toString()));\n"
"      stream.on(\"close\", (code: number) => {\n"
"        clearTimeout(timer);\n"
"        if (code !== 0 && !out && stderr) return reject(new Error(stderr.trim()));\n"
"        resolve((out + (stderr ? `\\n[stderr]: ${stderr}` : \"\")).trim());\n"
"      });\n"
"    });\n"
"  });\n"
"}\n"
"\n"
"async function exec(command: string, timeoutMs?: number): Promise<string> {\n"
"  const { timeoutMs: def } = getEnv();\n"
"  const { conn, release } = await getConn();\n"
"  try   { return await execOnConn(conn, command, timeoutMs ?? def); }\n"
"  finally { release(); }\n"
"}\n"
"\n"
"// --- Helpers ----------------------------------------------------------------\n"
"\n"
"const SAFE_NAME = /^[A-Z0-9_#@$]{1,10}$/i;\n"
"\n"
"function safeObjName(name: string, label = \"name\"): string {\n"
"  const n = name.trim().toUpperCase();\n"
"  if (!SAFE_NAME.test(n)) throw new Error(`Invalid IBM i ${label}: \"${name}\"`);\n"
"  return n;\n"
"}\n"
"\n"
"function libListPrefix(extra: string[] = []): string {\n"
"  const { libraryList } = getEnv();\n"
"  const libs = [...extra, ...libraryList].map(l => safeObjName(l, \"library\"));\n"
"  return `ADDLIBLE LIB(${libs.join(\" \")}) POSITION(*FIRST) ; `;\n"
"}\n"
"\n"
"async function execSql(sql: string, maxRows = 200): Promise<string> {\n"
"  const { libraryList, sqlTimeoutMs } = getEnv();\n"
"  const setup   = `ADDLIBLE LIB(${libraryList.join(\" \")}) POSITION(*FIRST) 2>/dev/null ; `;\n"
"  const escaped = sql.replace(/'/g, `'\\\\''`);\n"
"  return exec(`${setup}db2 '${escaped}' | head -${maxRows + 5}`, sqlTimeoutMs);\n"
"}\n"
"\n"
"const ok  = (text: string) => ({ content: [{ type: \"text\" as const, text }] });\n"
"const err = (msg:  string) => ({ content: [{ type: \"text\" as const, text: `Error: ${msg}` }], isError: true });\n"
"\n"
"function fmtRows(raw: string, maxRows = 200): string {\n"
"  const lines = raw.split(\"\\n\").filter(l => l.trim());\n"
"  if (lines.length > maxRows)\n"
"    return lines.slice(0, maxRows).join(\"\\n\") + `\\n... (truncated \u2014 ${lines.length} total rows)`;\n"
"  return lines.join(\"\\n\");\n"
"}\n"
"\n"
"// --- MCP Server -------------------------------------------------------------\n"
"\n"
"const server = new McpServer({ name: \"combank-ibmi-mcp\", version: \"1.0.0\" });\n"
"\n"
"// ===== GROUP 1 \u2014 Connection & Configuration =====\n"
"\n"
"server.registerTool(\"configure_connection\", {\n"
"  description: \"Set IBM i connection credentials and active environment. Persisted to .env.\",\n"
"  inputSchema: {\n"
"    environment:  z.enum([\"dev\",\"test\"]).describe(\"Target environment\").optional(),\n"
"    user:         z.string().describe(\"SSH username (e.g. lk08492)\").optional(),\n"
"    password:     z.string().describe(\"SSH password\").optional(),\n"
"    library_list: z.string().describe(\"Comma-separated library list (e.g. IV15LCL,DHUHILIB,SASHILIB)\").optional(),\n"
"  },\n"
"}, async ({ environment, user, password, library_list }) => {\n"
"  try {\n"
"    const patch: Parameters<typeof saveEnv>[0] = {};\n"
"    if (environment)  patch.activeEnv   = environment;\n"
"    if (user)         patch.user        = user;\n"
"    if (password)     patch.password    = password;\n"
"    if (library_list) patch.libraryList = library_list.split(\",\").map(s => s.trim());\n"
"    saveEnv(patch);\n"
"    const cfg    = getEnv();\n"
"    const envDef = ENVS[cfg.activeEnv];\n"
"    return ok(`Configured.\\nEnvironment : ${cfg.activeEnv} (${envDef.host}:${envDef.port})\\nUser        : ${cfg.user}\\nLibraries   : ${cfg.libraryList.join(\", \")}`);\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_connection_info\", {\n"
"  description: \"Show current IBM i connection settings. Password not shown.\",\n"
"  inputSchema: {},\n"
"}, async () => {\n"
"  const cfg    = getEnv();\n"
"  const envDef = ENVS[cfg.activeEnv];\n"
"  return ok(\n"
"    `Active environment : ${cfg.activeEnv}\\n` +\n"
"    `Host               : ${envDef?.host ?? \"unknown\"}\\n` +\n"
"    `Port               : ${envDef?.port ?? 22}\\n` +\n"
"    `User               : ${cfg.user}\\n` +\n"
"    `Password set       : ${cfg.password ? \"yes\" : \"NO \u2014 run configure_connection\"}\\n` +\n"
"    `Library list       : ${cfg.libraryList.join(\", \")}\\n` +\n"
"    `SSH timeout        : ${cfg.timeoutMs    / 1000}s\\n` +\n"
"    `SQL timeout        : ${cfg.sqlTimeoutMs / 1000}s\\n` +\n"
"    `Pool max           : ${cfg.poolMax}\\n`\n"
"  );\n"
"});\n"
"\n"
"server.registerTool(\"test_connection\", {\n"
"  description: \"Test SSH connectivity to IBM i.\",\n"
"  inputSchema: {\n"
"    environment: z.enum([\"dev\",\"test\"]).describe(\"Environment to test (defaults to active)\").optional(),\n"
"  },\n"
"}, async ({ environment }) => {\n"
"  try {\n"
"    if (environment) saveEnv({ activeEnv: environment });\n"
"    const result = await exec(`echo \"SSH OK\" && system \"DSPJOBLOG OUTPUT(*PRINT)\" 2>&1 | head -3`);\n"
"    return ok(`Connection test passed.\\n${result}`);\n"
"  } catch (e) { return err(`Connection test failed: ${e}`); }\n"
"});\n"
"\n"
"// ===== GROUP 2 \u2014 Library & Object Management =====\n"
"\n"
"server.registerTool(\"list_libraries\", {\n"
"  description: \"List DB2 libraries/schemas on IBM i, optionally filtered by name pattern.\",\n"
"  inputSchema: {\n"
"    name_filter: z.string().describe(\"Filter by name pattern (partial match, e.g. IV15)\").optional(),\n"
"    max_rows:    z.number().int().min(1).max(2000).describe(\"Max rows (default 200)\").optional(),\n"
"  },\n"
"}, async ({ name_filter, max_rows = 200 }) => {\n"
"  try {\n"
"    const where = name_filter ? `WHERE SCHEMA_NAME LIKE '%${name_filter.toUpperCase()}%'` : \"\";\n"
"    const sql   = `SELECT SCHEMA_NAME, SCHEMA_TEXT FROM QSYS2.SYSSCHEMAS ${where} ORDER BY SCHEMA_NAME FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"list_files\", {\n"
"  description: \"List all files (tables) in a specific IBM i library.\",\n"
"  inputSchema: {\n"
"    library:     z.string().describe(\"Library/schema name (e.g. FSVDATA)\"),\n"
"    name_filter: z.string().describe(\"Optional file name filter (partial match)\").optional(),\n"
"    max_rows:    z.number().int().min(1).max(2000).describe(\"Max rows (default 200)\").optional(),\n"
"  },\n"
"}, async ({ library, name_filter, max_rows = 200 }) => {\n"
"  try {\n"
"    const lib   = safeObjName(library, \"library\");\n"
"    const extra = name_filter ? `AND TABLE_NAME LIKE '%${name_filter.toUpperCase()}%'` : \"\";\n"
"    const sql   = `SELECT TABLE_NAME, TABLE_TEXT, TABLE_TYPE FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = '${lib}' ${extra} ORDER BY TABLE_NAME FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"describe_file\", {\n"
"  description: \"Show complete field/column structure of an IBM i file.\",\n"
"  inputSchema: {\n"
"    library:   z.string().describe(\"Library name\"),\n"
"    file_name: z.string().describe(\"File/table name (e.g. CSTMAST)\"),\n"
"  },\n"
"}, async ({ library, file_name }) => {\n"
"  try {\n"
"    const lib = safeObjName(library, \"library\");\n"
"    const fil = safeObjName(file_name, \"file\");\n"
"    const sql = `SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_TEXT FROM QSYS2.SYSCOLUMNS WHERE TABLE_SCHEMA = '${lib}' AND TABLE_NAME = '${fil}' ORDER BY ORDINAL_POSITION`;\n"
"    return ok(fmtRows(await execSql(sql, 500), 500));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_file_keys\", {\n"
"  description: \"Show key fields (primary key / access paths) for an IBM i file.\",\n"
"  inputSchema: {\n"
"    library:   z.string().describe(\"Library name\"),\n"
"    file_name: z.string().describe(\"File/table name\"),\n"
"  },\n"
"}, async ({ library, file_name }) => {\n"
"  try {\n"
"    const lib = safeObjName(library, \"library\");\n"
"    const fil = safeObjName(file_name, \"file\");\n"
"    const sql = `SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, ORDERING FROM QSYS2.SYSKEYS WHERE INDEX_SCHEMA = '${lib}' AND INDEX_NAME = '${fil}' ORDER BY COLUMN_POSITION`;\n"
"    return ok(fmtRows(await execSql(sql)));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"search_files_by_field\", {\n"
"  description: \"Find all files containing a specific field name across one or all libraries.\",\n"
"  inputSchema: {\n"
"    field_name: z.string().describe(\"Field name to search for (partial match, e.g. ACCTNO)\"),\n"
"    library:    z.string().describe(\"Library to search, or *ALL for all libraries\").optional(),\n"
"    max_rows:   z.number().int().min(1).max(500).describe(\"Max results (default 100)\").optional(),\n"
"  },\n"
"}, async ({ field_name, library = \"*ALL\", max_rows = 100 }) => {\n"
"  try {\n"
"    const libC = library !== \"*ALL\" ? `AND TABLE_SCHEMA = '${safeObjName(library, \"library\")}'` : \"\";\n"
"    const sql  = `SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, COLUMN_TEXT FROM QSYS2.SYSCOLUMNS WHERE COLUMN_NAME LIKE '%${field_name.toUpperCase()}%' ${libC} ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"list_objects\", {\n"
"  description: \"List objects (programs, files, data areas, etc.) in a library filtered by type and name.\",\n"
"  inputSchema: {\n"
"    library:     z.string().describe(\"Library name\"),\n"
"    obj_type:    z.string().describe(\"Object type: *ALL, *PGM, *SRVPGM, *MODULE, *FILE, *DTAARA, *CMD\").optional(),\n"
"    name_filter: z.string().describe(\"Object name filter (supports * wildcard)\").optional(),\n"
"    max_rows:    z.number().int().min(1).max(2000).describe(\"Max results (default 200)\").optional(),\n"
"  },\n"
"}, async ({ library, obj_type = \"*ALL\", name_filter = \"*ALL\", max_rows = 200 }) => {\n"
"  try {\n"
"    const lib   = safeObjName(library, \"library\");\n"
"    const typeC = obj_type    !== \"*ALL\" ? `AND OBJECT_TYPE = '${obj_type.replace(\"*\",\"\")}'`                              : \"\";\n"
"    const nameC = name_filter !== \"*ALL\" ? `AND OBJECT_NAME LIKE '${name_filter.replace(\"*\",\"%\").toUpperCase()}%'` : \"\";\n"
"    const sql   = `SELECT OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE, OBJECT_TEXT FROM QSYS2.OBJECT_STATISTICS WHERE OBJECT_SCHEMA = '${lib}' ${typeC} ${nameC} FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// ===== GROUP 3 \u2014 Source Code Management =====\n"
"\n"
"server.registerTool(\"list_source_members\", {\n"
"  description: \"List source members in a source physical file (e.g. QRPGLESRC, QCLLESRC).\",\n"
"  inputSchema: {\n"
"    library:       z.string().describe(\"Library name (e.g. FSVPGM)\"),\n"
"    source_file:   z.string().describe(\"Source file name (e.g. QRPGLESRC, QCLLESRC)\"),\n"
"    member_filter: z.string().describe(\"Member name filter (supports * wildcard, or *ALL)\").optional(),\n"
"    max_rows:      z.number().int().min(1).max(2000).describe(\"Max rows (default 200)\").optional(),\n"
"  },\n"
"}, async ({ library, source_file, member_filter = \"*ALL\", max_rows = 200 }) => {\n"
"  try {\n"
"    const lib    = safeObjName(library, \"library\");\n"
"    const spf    = safeObjName(source_file, \"source_file\");\n"
"    const filter = member_filter === \"*ALL\" ? \"\" : member_filter.replace(\"*\", \"%\").toUpperCase();\n"
"    const nameC  = filter ? `AND SOURCE_MEMBER LIKE '${filter}'` : \"\";\n"
"    const sql    = `SELECT SOURCE_MEMBER, SOURCE_TYPE, SOURCE_TEXT, LAST_CHANGE_DATE FROM QSYS2.MEMBER_INFO WHERE SOURCE_FILE_LIBRARY = '${lib}' AND SOURCE_FILE = '${spf}' ${nameC} ORDER BY SOURCE_MEMBER FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"view_source_member\", {\n"
"  description: \"View source code of a specific member. Uses EBCDIC\\u2192UTF-8 conversion.\",\n"
"  inputSchema: {\n"
"    library:     z.string().describe(\"Library name (e.g. FSVPGM)\"),\n"
"    source_file: z.string().describe(\"Source physical file (e.g. QRPGLESRC, QCLLESRC)\"),\n"
"    member:      z.string().describe(\"Source member name (e.g. AR002)\"),\n"
"    max_lines:   z.number().int().min(1).max(5000).describe(\"Max lines (default 500)\").optional(),\n"
"  },\n"
"}, async ({ library, source_file, member, max_lines = 500 }) => {\n"
"  try {\n"
"    const lib      = safeObjName(library, \"library\");\n"
"    const spf      = safeObjName(source_file, \"source_file\");\n"
"    const mbr      = safeObjName(member, \"member\");\n"
"    const qsysPath = `/QSYS.LIB/${lib}.LIB/${spf}.FILE/${mbr}.MBR`;\n"
"    const cmd      = `/QOpenSys/usr/bin/iconv -f IBM-037 -t UTF-8 \"${qsysPath}\" 2>/dev/null | head -${max_lines}`;\n"
"    return ok((await exec(cmd, getEnv().sqlTimeoutMs)) || \"(empty member)\");\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"search_source_members\", {\n"
"  description: \"Search source member names across a library by name pattern or type.\",\n"
"  inputSchema: {\n"
"    library:        z.string().describe(\"Library to search in\"),\n"
"    member_pattern: z.string().describe(\"Member name pattern (partial match)\").optional(),\n"
"    source_type:    z.string().describe(\"Source type filter (e.g. RPGLE, CLLE, DSPF, PF)\").optional(),\n"
"    max_rows:       z.number().int().min(1).max(500).describe(\"Max results (default 100)\").optional(),\n"
"  },\n"
"}, async ({ library, member_pattern, source_type, max_rows = 100 }) => {\n"
"  try {\n"
"    const lib     = safeObjName(library, \"library\");\n"
"    const clauses = [];\n"
"    if (member_pattern) clauses.push(`SOURCE_MEMBER LIKE '%${member_pattern.toUpperCase()}%'`);\n"
"    if (source_type)    clauses.push(`SOURCE_TYPE = '${source_type.toUpperCase()}'`);\n"
"    const where   = clauses.length ? \"AND \" + clauses.join(\" AND \") : \"\";\n"
"    const sql     = `SELECT SOURCE_FILE_LIBRARY, SOURCE_FILE, SOURCE_MEMBER, SOURCE_TYPE, SOURCE_TEXT FROM QSYS2.MEMBER_INFO WHERE SOURCE_FILE_LIBRARY = '${lib}' ${where} ORDER BY SOURCE_MEMBER FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_program_info\", {\n"
"  description: \"Get detailed information about a compiled program object.\",\n"
"  inputSchema: {\n"
"    library:      z.string().describe(\"Library name\"),\n"
"    program_name: z.string().describe(\"Program name\"),\n"
"  },\n"
"}, async ({ library, program_name }) => {\n"
"  try {\n"
"    const lib = safeObjName(library, \"library\");\n"
"    const pgm = safeObjName(program_name, \"program\");\n"
"    const sql = `SELECT PROGRAM_SCHEMA, PROGRAM_NAME, PROGRAM_TYPE, CREATION_TIMESTAMP, SOURCE_FILE, SOURCE_LIBRARY, SOURCE_MEMBER, PROGRAM_LANGUAGE FROM QSYS2.PROGRAM_INFO WHERE PROGRAM_SCHEMA = '${lib}' AND PROGRAM_NAME = '${pgm}'`;\n"
"    return ok(fmtRows(await execSql(sql)));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// ===== GROUP 4 \u2014 SQL Query Execution =====\n"
"\n"
"server.registerTool(\"run_sql_query\", {\n"
"  description: \"Execute any SQL SELECT query against IBM i DB2. Library list is automatically prepended.\",\n"
"  inputSchema: {\n"
"    sql:      z.string().describe(\"SQL SELECT statement to execute\"),\n"
"    max_rows: z.number().int().min(1).max(1000).describe(\"Max rows (default 200)\").optional(),\n"
"  },\n"
"}, async ({ sql, max_rows = 200 }) => {\n"
"  try {\n"
"    const t = sql.trim().toUpperCase();\n"
"    if (!t.startsWith(\"SELECT\") && !t.startsWith(\"WITH\") && !t.startsWith(\"VALUES\"))\n"
"      return err(\"Only SELECT/WITH/VALUES queries allowed.\");\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"search_data_in_file\", {\n"
"  description: \"Search records in any IBM i file with up to 3 field/value filters.\",\n"
"  inputSchema: {\n"
"    library:   z.string().describe(\"Library name\"),\n"
"    file_name: z.string().describe(\"File/table name\"),\n"
"    field1: z.string().describe(\"First field name to filter on\").optional(),\n"
"    value1: z.string().describe(\"Value to match for field1\").optional(),\n"
"    field2: z.string().describe(\"Second field name to filter on\").optional(),\n"
"    value2: z.string().describe(\"Value to match for field2\").optional(),\n"
"    field3: z.string().describe(\"Third field name to filter on\").optional(),\n"
"    value3: z.string().describe(\"Value to match for field3\").optional(),\n"
"    max_rows: z.number().int().min(1).max(500).describe(\"Max records (default 50)\").optional(),\n"
"  },\n"
"}, async ({ library, file_name, field1, value1, field2, value2, field3, value3, max_rows = 50 }) => {\n"
"  try {\n"
"    const lib     = safeObjName(library, \"library\");\n"
"    const fil     = safeObjName(file_name, \"file\");\n"
"    const clauses: string[] = [];\n"
"    if (field1 && value1) clauses.push(`${field1.toUpperCase()} = '${value1}'`);\n"
"    if (field2 && value2) clauses.push(`${field2.toUpperCase()} = '${value2}'`);\n"
"    if (field3 && value3) clauses.push(`${field3.toUpperCase()} = '${value3}'`);\n"
"    const where   = clauses.length ? \"WHERE \" + clauses.join(\" AND \") : \"\";\n"
"    const sql     = `SELECT * FROM ${lib}.${fil} ${where} FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"describe_sql_object\", {\n"
"  description: \"Show metadata for an IBM i database object (TABLE, VIEW, PROCEDURE, etc.).\",\n"
"  inputSchema: {\n"
"    object_name:    z.string().describe(\"Object name\"),\n"
"    object_library: z.string().describe(\"Library where the object lives\").optional(),\n"
"    object_type:    z.enum([\"TABLE\",\"VIEW\",\"INDEX\",\"PROCEDURE\",\"FUNCTION\",\"TRIGGER\",\"ALIAS\",\"SEQUENCE\"]).describe(\"Object type (default TABLE)\").optional(),\n"
"  },\n"
"}, async ({ object_name, object_library = \"QSYS2\", object_type = \"TABLE\" }) => {\n"
"  try {\n"
"    const obj = safeObjName(object_name, \"object\");\n"
"    const lib = safeObjName(object_library, \"library\");\n"
"    const sql = object_type === \"TABLE\"\n"
"      ? `SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, TABLE_TEXT FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = '${lib}' AND TABLE_NAME = '${obj}'`\n"
"      : `SELECT ROUTINE_SCHEMA, ROUTINE_NAME, ROUTINE_TYPE, CAST(ROUTINE_DEFINITION AS VARCHAR(4000)) AS DEF FROM QSYS2.SYSROUTINES WHERE ROUTINE_SCHEMA = '${lib}' AND ROUTINE_NAME = '${obj}'`;\n"
"    return ok(fmtRows(await execSql(sql)));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// ===== GROUP 5 \u2014 CL Command Execution =====\n"
"\n"
"server.registerTool(\"execute_cl_command\", {\n"
"  description: \"Execute a CL command on IBM i via SSH. Library list is prepended automatically.\",\n"
"  inputSchema: {\n"
"    command:          z.string().describe(\"CL command to execute (e.g. DSPLIB QGPL)\"),\n"
"    add_library_list: z.boolean().describe(\"Prepend configured library list (default true)\").optional(),\n"
"  },\n"
"}, async ({ command, add_library_list = true }) => {\n"
"  try {\n"
"    const prefix = add_library_list ? libListPrefix() : \"\";\n"
"    const safe   = command.replace(/\"/g, '\\\\\"');\n"
"    return ok((await exec(`${prefix}system \"${safe}\" 2>&1`)) || \"(no output)\");\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"execute_pase_command\", {\n"
"  description: \"Execute a raw PASE/shell command on IBM i (advanced use).\",\n"
"  inputSchema: {\n"
"    command: z.string().describe(\"Shell command to execute in IBM i PASE environment\"),\n"
"  },\n"
"}, async ({ command }) => {\n"
"  try { return ok((await exec(command)) || \"(no output)\"); }\n"
"  catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// ===== GROUP 6 \u2014 Job & System Monitoring =====\n"
"\n"
"server.registerTool(\"list_active_jobs\", {\n"
"  description: \"List currently active jobs on IBM i.\",\n"
"  inputSchema: {\n"
"    user_filter:      z.string().describe(\"Filter by user name, or *ALL\").optional(),\n"
"    subsystem_filter: z.string().describe(\"Filter by subsystem name, or *ALL\").optional(),\n"
"    max_rows:         z.number().int().min(1).max(200).describe(\"Max jobs (default 50)\").optional(),\n"
"  },\n"
"}, async ({ user_filter = \"*ALL\", subsystem_filter = \"*ALL\", max_rows = 50 }) => {\n"
"  try {\n"
"    const uC  = user_filter      !== \"*ALL\" ? `AND AUTHORIZATION_NAME = '${user_filter.toUpperCase()}'`  : \"\";\n"
"    const sC  = subsystem_filter !== \"*ALL\" ? `AND SUBSYSTEM = '${subsystem_filter.toUpperCase()}'`       : \"\";\n"
"    const sql = `SELECT JOB_NAME, AUTHORIZATION_NAME, JOB_STATUS, SUBSYSTEM, CPU_TIME, FUNCTION FROM QSYS2.ACTIVE_JOB_INFO WHERE 1=1 ${uC} ${sC} ORDER BY CPU_TIME DESC FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_job_log\", {\n"
"  description: \"Get recent messages from a specific IBM i job log.\",\n"
"  inputSchema: {\n"
"    job_name:     z.string().describe(\"Fully qualified job name in format NUMBER/USER/NAME\"),\n"
"    max_rows:     z.number().int().min(1).max(500).describe(\"Max log entries (default 100)\").optional(),\n"
"    min_severity: z.number().int().min(0).max(99).describe(\"Min severity: 0=info, 20=warning, 30=error\").optional(),\n"
"  },\n"
"}, async ({ job_name, max_rows = 100, min_severity = 0 }) => {\n"
"  try {\n"
"    const parts = job_name.split(\"/\");\n"
"    if (parts.length !== 3) return err(\"Job name must be NUMBER/USER/NAME\");\n"
"    const [jobNbr, jobUser, jobName] = parts;\n"
"    const sql = `SELECT MESSAGE_TIMESTAMP, MESSAGE_ID, MESSAGE_TYPE, MESSAGE_SEVERITY, MESSAGE_TEXT FROM QSYS2.JOBLOG_INFO('${jobName}', '${jobUser}', '${jobNbr}') WHERE MESSAGE_SEVERITY >= ${min_severity} ORDER BY MESSAGE_TIMESTAMP DESC FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"check_message_queue\", {\n"
"  description: \"Check messages in a message queue (e.g. QSYSOPR, QHST) for system alerts.\",\n"
"  inputSchema: {\n"
"    queue_name:    z.string().describe(\"Message queue name (e.g. QSYSOPR, QHST)\").optional(),\n"
"    queue_library: z.string().describe(\"Message queue library (default QSYS)\").optional(),\n"
"    max_rows:      z.number().int().min(1).max(200).describe(\"Max messages (default 50)\").optional(),\n"
"    min_severity:  z.number().int().min(0).max(99).describe(\"Min severity (0=all, 30=errors)\").optional(),\n"
"  },\n"
"}, async ({ queue_name = \"QSYSOPR\", queue_library = \"QSYS\", max_rows = 50, min_severity = 0 }) => {\n"
"  try {\n"
"    const q    = safeObjName(queue_name, \"queue\");\n"
"    const qlib = safeObjName(queue_library, \"queue_library\");\n"
"    return ok(fmtRows(await exec(`system \"DSPMSG MSGQ(${qlib}/${q}) SEV(${min_severity})\" 2>&1 | head -${max_rows * 3}`), max_rows * 3));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_system_disk_usage\", {\n"
"  description: \"Check disk usage and ASP utilization.\",\n"
"  inputSchema: {},\n"
"}, async () => {\n"
"  try {\n"
"    return ok(fmtRows(await execSql(`SELECT ASP_NUMBER, RESOURCE_NAME, ASP_TYPE, TOTAL_CAPACITY, TOTAL_CAPACITY_AVAILABLE FROM QSYS2.ASP_INFO`)));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_system_values\", {\n"
"  description: \"Read IBM i system values (date/time format, security settings, etc.).\",\n"
"  inputSchema: {\n"
"    sysval_filter: z.string().describe(\"Filter by system value name (e.g. QDATE, QTIME, or *ALL)\").optional(),\n"
"    max_rows:      z.number().int().min(1).max(200).describe(\"Max values (default 50)\").optional(),\n"
"  },\n"
"}, async ({ sysval_filter = \"*ALL\", max_rows = 50 }) => {\n"
"  try {\n"
"    const where = sysval_filter !== \"*ALL\" ? `WHERE SYSTEM_VALUE_NAME LIKE '%${sysval_filter.toUpperCase()}%'` : \"\";\n"
"    const sql   = `SELECT SYSTEM_VALUE_NAME, CURRENT_NUMERIC_VALUE, CURRENT_CHARACTER_VALUE FROM QSYS2.SYSTEM_VALUE_INFO ${where} FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_sql_history\", {\n"
"  description: \"View recent SQL statements executed on the IBM i system.\",\n"
"  inputSchema: {\n"
"    job_filter: z.string().describe(\"Filter by job name (partial match), or empty for all\").optional(),\n"
"    max_rows:   z.number().int().min(1).max(200).describe(\"Max statements (default 50)\").optional(),\n"
"  },\n"
"}, async ({ job_filter = \"\", max_rows = 50 }) => {\n"
"  try {\n"
"    const jobC = job_filter ? `WHERE JOB_NAME LIKE '%${job_filter.toUpperCase()}%'` : \"\";\n"
"    const sql  = `SELECT JOB_NAME, QUERY_USE_TIME, QUERY_READS, STATEMENT_TEXT FROM QSYS2.SQL_ACTIVITY ${jobC} ORDER BY QUERY_USE_TIME DESC FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// ===== GROUP 7 \u2014 Impact Analysis & Auditing =====\n"
"\n"
"server.registerTool(\"find_programs_using_file\", {\n"
"  description: \"Find all programs that reference a specific file \u2014 impact analysis for schema changes.\",\n"
"  inputSchema: {\n"
"    file_name:    z.string().describe(\"File name to find references for (partial match)\"),\n"
"    file_library: z.string().describe(\"Library containing the file\").optional(),\n"
"    max_rows:     z.number().int().min(1).max(500).describe(\"Max results (default 100)\").optional(),\n"
"  },\n"
"}, async ({ file_name, file_library, max_rows = 100 }) => {\n"
"  try {\n"
"    const libC = file_library ? `AND OBJECT_SCHEMA = '${safeObjName(file_library, \"file_library\")}'` : \"\";\n"
"    const sql  = `SELECT PROGRAM_SCHEMA, PROGRAM_NAME, OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE FROM QSYS2.PROGRAM_INFO WHERE OBJECT_NAME LIKE '%${file_name.toUpperCase()}%' ${libC} FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_table_changes\", {\n"
"  description: \"Retrieve recent INSERT/UPDATE/DELETE changes via DB2 journal \u2014 for auditing.\",\n"
"  inputSchema: {\n"
"    journal_library: z.string().describe(\"Library containing the journal\"),\n"
"    journal_name:    z.string().describe(\"Journal name (e.g. QSJJRN, FSRJRN)\"),\n"
"    file_name:       z.string().describe(\"File to audit\"),\n"
"    file_library:    z.string().describe(\"Library containing the file\"),\n"
"    hours:           z.number().int().min(1).max(720).describe(\"Look back this many hours (default 24)\").optional(),\n"
"    max_rows:        z.number().int().min(1).max(500).describe(\"Max journal entries (default 100)\").optional(),\n"
"  },\n"
"}, async ({ journal_library, journal_name, file_name, file_library, hours = 24, max_rows = 100 }) => {\n"
"  try {\n"
"    const jlib = safeObjName(journal_library, \"journal_library\");\n"
"    const jrn  = safeObjName(journal_name, \"journal\");\n"
"    const flib = safeObjName(file_library, \"file_library\");\n"
"    const fil  = safeObjName(file_name, \"file\");\n"
"    const sql  = `SELECT ENTRY_TIMESTAMP, JOURNAL_CODE, ENTRY_TYPE, JOB_NAME, USER_NAME FROM TABLE(QSYS2.DISPLAY_JOURNAL(JOURNAL_LIBRARY => '${jlib}', JOURNAL_NAME => '${jrn}', OBJECT_SCHEMA => '${flib}', OBJECT_NAME => '${fil}', STARTING_TIMESTAMP => CURRENT_TIMESTAMP - ${hours} HOURS)) WHERE JOURNAL_CODE IN ('R') ORDER BY ENTRY_TIMESTAMP DESC FETCH FIRST ${max_rows} ROWS ONLY`;\n"
"    return ok(fmtRows(await execSql(sql, max_rows), max_rows));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"get_library_list\", {\n"
"  description: \"Show the current job's library list.\",\n"
"  inputSchema: {},\n"
"}, async () => {\n"
"  try {\n"
"    return ok(fmtRows(await execSql(`SELECT ORDINAL_POSITION, SCHEMA_NAME, SCHEMA_TEXT, TYPE FROM QSYS2.LIBRARY_LIST_INFO ORDER BY ORDINAL_POSITION`)));\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"server.registerTool(\"read_data_area\", {\n"
"  description: \"Read a data area (*DTAARA) \u2014 commonly used for configuration and control values.\",\n"
"  inputSchema: {\n"
"    library:   z.string().describe(\"Library containing the data area(s)\"),\n"
"    area_name: z.string().describe(\"Data area name, or *ALL for all data areas in the library\").optional(),\n"
"  },\n"
"}, async ({ library, area_name = \"*ALL\" }) => {\n"
"  try {\n"
"    const lib = safeObjName(library, \"library\");\n"
"    if (area_name === \"*ALL\") {\n"
"      return ok(fmtRows(await execSql(`SELECT DATA_AREA_SCHEMA, DATA_AREA_NAME, DATA_AREA_TYPE, LENGTH, DATA_AREA_VALUE FROM QSYS2.DATA_AREA_INFO WHERE DATA_AREA_SCHEMA = '${lib}'`)));\n"
"    }\n"
"    const da = safeObjName(area_name, \"area\");\n"
"    return ok((await exec(`system \"RTVDTAARA DTAARA(${lib}/${da})\" 2>&1`)) || \"(empty)\");\n"
"  } catch (e) { return err(String(e)); }\n"
"});\n"
"\n"
"// --- Start Server -----------------------------------------------------------\n"
"\n"
"const transport = new StdioServerTransport();\n"
"await server.connect(transport);\n"
)
# fmt: on

OUT.write_text(TS, encoding='utf-8')
lines = TS.count('\n')
print(f"Written {OUT}")
print(f"  {len(TS):,} chars  |  {lines} lines")
